import { ShieldCheck, FileText, ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

function Legal() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 transition-colors duration-300 py-16 px-6">
      <div className="max-w-5xl mx-auto">

        <Link
          to="/"
          className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 font-medium mb-10"
        >
          <ArrowLeft size={18} />
          Back to Home
        </Link>

        <div className="text-center mb-14">
          <h1 className="text-5xl font-bold tracking-tight text-slate-900 dark:text-white">
  Privacy Policy &
  <span className="block text-blue-600 dark:text-blue-400">
    Medical Disclaimer
  </span>
</h1>

        </div>

        <div className="flex justify-center gap-4 mb-10">
  <a
    href="#privacy"
    className="px-5 py-2 rounded-full bg-blue-600 text-white hover:bg-blue-700 transition"
  >
    Privacy Policy
  </a>

  <a
    href="#disclaimer"
    className="px-5 py-2 rounded-full border border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
  >
    Medical Disclaimer
  </a>
</div>

        {/* Privacy Policy */}

        <div id="privacy" className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-lg p-10 mb-10">

          <div className="flex items-center gap-3 mb-8">

            <div className="w-12 h-12 rounded-2xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">

              <FileText className="text-blue-600 dark:text-blue-400" />

            </div>

            <h2 className="text-3xl font-bold text-slate-900 dark:text-white">
              Privacy Policy
            </h2>

          </div>

          <div className="space-y-6 text-slate-600 dark:text-slate-300 leading-8">

            <div>
              <h3 className="font-semibold text-slate-900 dark:text-white mb-2">
                Information Collection
              </h3>

              <p>
                MedExplain AI processes uploaded medical reports solely to
                generate AI-powered explanations. We do not permanently store
                your medical reports or personal health information.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-slate-900 dark:text-white mb-2">
                Data Security
              </h3>

              <p>
                All uploaded files are securely transmitted for processing.
                Protecting your privacy and data is one of our highest
                priorities.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-slate-900 dark:text-white mb-2">
                Third-Party Services
              </h3>

              <p>
                MedExplain AI uses trusted AI providers to analyze reports.
                Uploaded content is processed only to generate your requested
                analysis.
              </p>
            </div>

          </div>

        </div>

        {/* Disclaimer */}

        <div id="disclaimer" className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-lg p-10">

          <div className="flex items-center gap-3 mb-8">

            <div className="w-12 h-12 rounded-2xl bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">

              <ShieldCheck className="text-amber-600 dark:text-amber-400" />

            </div>

            <h2 className="text-3xl font-bold text-slate-900 dark:text-white">
              Medical Disclaimer
            </h2>

          </div>

          <div className="space-y-6 text-slate-600 dark:text-slate-300 leading-8">

            <p>
              MedExplain AI is intended solely for educational and informational
              purposes.
            </p>

            <p>
              The analysis generated by this application does not constitute
              medical advice, diagnosis, or treatment.
            </p>

            <p>
              Always consult a qualified healthcare professional regarding any
              medical condition, laboratory result, or treatment decision.
            </p>

            <p>
              Never ignore professional medical advice or delay seeking medical
              attention based on information provided by this application.
            </p>

            <p>
              If you believe you are experiencing a medical emergency,
              immediately contact your doctor or local emergency services.
            </p>

          </div>

        </div>

      </div>
    </div>
  );
}

export default Legal;